name: Airlog Send Last 100 Commit Messages
on:
  workflow_dispatch:  # Allows manual trigger
jobs:
    get-last-100-commit-messages:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Get last 20 commit logs, Base64 encode, and write to file
          run: |
            for idx in {1..4}; do
              log=$(git log --skip=$idx --max-count=1 -p --no-merges --stat \
                --format="§§§§%H§§%ad§§%B" \
                --date=format:"%Y-%m-%dT%H:%M:%SZ" \
                -- . ':(exclude).github')
              if [ -z "$log" ]; then
                break
              fi
              echo "$log" | base64 > "gitlog_base64_$idx.txt"
            done

        - name: Read encoded log and trigger webhook
          env:
            GITHUB_EVENT: ${{ toJson(github.event.commits[0]) }}
          run: |
            for idx in {1..4}; do
              if [ ! -f "gitlog_base64_$idx.txt" ]; then
                break
              fi
              ENCODED_LOG=$(cat "gitlog_base64_$idx.txt")

              echo ENCODED_LOG

              # Write the JSON data to a file
              echo "{\"diff\": \"$ENCODED_LOG\"}" > json_payload_$idx.json

              echo "NINJA"

              # Read the file with jq to properly format it
              JSON_PAYLOAD=$(jq . json_payload_$idx.json)
              echo "JSON_PAYLOAD: $JSON_PAYLOAD"

              curl -X POST -H "Content-Type: application/json" \
              -H "Authorization: Bearer f654da:u3b7yCitMe8nRhRpsF6l" \
              -d @json_payload_$idx.json "https://056b-213-66-90-230.ngrok-free.app/webhooks/github_actions"
            done
