name: Airlog Send Last 100 Commit Messages
on:
  workflow_dispatch:  # Allows manual trigger
jobs:
    get-last-100-commit-messages:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Get last 20 commit logs, Base64 encode, and write to file
          run: |
            # count=$(git rev-list --count --all --no-merges  -- . ':(exclude).github')
            # count=$((count - 1))

            for idx in {0..20}; do
              log=$(git log --skip=$idx --max-count=1 -p --no-merges --stat \
                --format="§§§§%H§§%ad§§%B" \
                --date=format:"%Y-%m-%dT%H:%M:%SZ" \
                -- . ':(exclude).github')
              if [ -z "$log" ]; then
                break
              fi
              echo "$log" | base64 > "gitlog_base64_$idx.txt"
            done

        - name: Read encoded log and trigger webhook
          run: |
            # count=$(git rev-list --count --all --no-merges  -- . ':(exclude).github')
            # count=$((count - 1))

            for idx in {0..20}; do
              if [ ! -f "gitlog_base64_$idx.txt" ]; then
                break
              fi

              ENCODED_LOG=$(cat "gitlog_base64_$idx.txt")

              # Create a JSON file using heredoc to properly manage new lines and escaping
              cat << EOF > payload.json
              {
                "diff": "$ENCODED_LOG"
              }
              EOF

              echo $(cat payload.json)

              # Use jq to read from file, ensuring proper parsing and escaping
              JSON_PAYLOAD=$(jq . payload.json)

              curl -X POST -H "Content-Type: application/json" \
              -H "Authorization: Bearer f654da:u3b7yCitMe8nRhRpsF6l" \
              -d "$JSON_PAYLOAD" "https://016e-213-66-90-230.ngrok-free.app/webhooks/github_actions"
            done
